name: deploy-rfc-book

on:
  push:
    branches:
      - master
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate the src directory
        run: ./generate-src-dir.sh

      - name: Install mdbook-mermaid
        env:
          LINK: https://github.com/badboy/mdbook-mermaid/releases/download
          VERSION: 0.7.1
          FILENAME: mdbook-mermaid-v0.7.1-x86_64-unknown-linux-gnu.tar.gz
        run: curl -L "$LINK/v$VERSION/$FILENAME" | tar xz -C $HOME/.cargo/bin

      - name: Run mdbook-mermaid
        run: mdbook-mermaid install .

      - name: Deploy the book to GitHub Pages
        uses: XAMPPRocky/deploy-mdbook@v1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
