name: Render a RFC

on:
  pull_request:
    branches:
      - master

jobs:
  render-rfc:

    if: contains(github.event.pull_request.labels.*.names, 'rfc-approved') == false

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Run RFC rendering script
        id: script
        run: |
          RETURN_VALUE=$(./render-rfc.sh ${{ github.head_ref }})
          echo "::set-output name=RETURN_VALUE::$RETURN_VALUE"

      - name: Push to the render repository
        if: ${{ steps.script.outputs.RETURN_VALUE}} == '0'
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ${{ github.head_ref }}
