name: Render a RFC

on:
  pull_request:
    branches:
      - master

jobs:
  render-rfc:

    if: contains(github.event.pull_request.labels.*.names, 'rfc-approved') == false

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Run RFC rendering script
        id: script
        run: |
          RETURN_VALUE=$(./render-rfc.sh ${{ github.head_ref }})
          echo "::set-output name=RETURN_VALUE::$RETURN_VALUE"

      - name: Create the commit for the RFC rendering repository
        if: ${{ steps.script.outputs.RETURN_VALUE}} == '0'
        env:
          LINK: https://github.com/sifis-home/wp2-rfcs-rendering
        run: |
          git clone $LINK wp2-rendering
          mv ${{ github.head_ref }}/ wp2-rendering/
          cd wp2-rendering
          git config --local user.email "sifis-home-wp2@sifis.org"
          git config --local user.name "sifis-home[bot]"
          git add .
          git commit -m "Update ${{ github.head_ref }} RFC"

      - name: Push changes
        if: ${{ steps.script.outputs.RETURN_VALUE}} == '0'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          branch: master
          directory: wp2-rendering
          repository: wp2-rfcs-rendering
